import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'akh' at '5/21/18 4:45 PM' with Gradle 2.4
 *
 * @author akh, @date 5/21/18 4:45 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Object classUnderTest = new Object();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.equals(classUnderTest));
    }
}
